#!/usr/bin/env node
// EXPORTARMOURY — the shop's catalogue, out of the code that owns it.
//
//   node tools/blender/exportarmoury.mjs
//
// ARMOURY lives in src/game/client/characters.ts: fifty-nine priced options
// across every slot, with the prices measured against what a match actually
// pays and a long note saying so. The Unity client needs all of it, and there
// are exactly two ways to give it: copy it into C#, or export it.
//
// COPYING IT WOULD BE THE THIRD TIME. attackDir was on the wire and thrown
// away; deathZone was on the wire and thrown away; a second hand-kept copy of a
// fifty-nine-row price list would be wrong within a week and nothing would say
// so. So it is exported, once, from the file that owns it, and armourytest is
// the gate that the shipped copy still matches.
import { spawnSync } from "child_process";
import { rmSync, mkdirSync, existsSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { resolve, dirname } from "path";
import { pathToFileURL, fileURLToPath } from "url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const OUT = resolve(ROOT, ".exportarmoury");
const SHIP = resolve(ROOT, "BRETWALDA - Blood Moot/Assets/StreamingAssets");

rmSync(OUT, { recursive: true, force: true }); mkdirSync(OUT, { recursive: true });
const tsc = spawnSync("npx", ["tsc", "src/game/client/characters.ts", "--outDir", ".exportarmoury",
  "--target", "es2022", "--module", "esnext", "--moduleResolution", "bundler", "--skipLibCheck"],
  { cwd: ROOT, encoding: "utf8" });

const emitted = [];
const walk = (d) => { for (const e of readdirSync(d, { withFileTypes: true })) {
  const f = resolve(d, e.name); if (e.isDirectory()) walk(f); else if (e.name.endsWith(".js")) emitted.push(f); } };
if (existsSync(OUT)) walk(OUT);
for (const f of emitted) {
  const src = readFileSync(f, "utf8");
  const fixed = src.replace(/(from\s+")(\.[^"]*?)(")/g, (m, a, b, c) => (b.endsWith(".js") ? m : a + b + ".js" + c))
    .replace(/(from\s+")@\/game\/([^"]*)(")/g, (m, a, b, c) => a + pathToFileURL(resolve(ROOT, "src/game", b)).href + c);
  if (fixed !== src) writeFileSync(f, fixed);
}
const built = emitted.find((f) => f.endsWith("characters.js"));
if (!built) { console.error("[exportarmoury] tsc emitted nothing:\n" + (tsc.stdout || "") + (tsc.stderr || "")); process.exit(2); }

const mod = await import(pathToFileURL(built).href);
const ARMOURY = mod.ARMOURY;
if (!Array.isArray(ARMOURY) || ARMOURY.length === 0) { console.error("[exportarmoury] no ARMOURY exported"); process.exit(2); }
const free = typeof mod.freeCosmeticIds === "function" ? mod.freeCosmeticIds() : [];

// Only what a shop screen needs. The geometry stays in the models; this is the
// price list and the names on it.
const out = {
  note: "Generated by tools/blender/exportarmoury.mjs from ARMOURY in characters.ts. Do not hand-edit; run the tool.",
  free: [...free],
  slots: ARMOURY.map((s) => ({
    slot: s.slot,
    label: s.label,
    options: s.options.map((o) => ({
      id: o.id, label: o.label, cost: o.cost ?? 0,
      ...(o.people ? { people: o.people } : {}),
      ...(o.cls ? { cls: o.cls } : {}),
    })),
  })),
};
mkdirSync(SHIP, { recursive: true });
const path = resolve(SHIP, "armoury.json");
const text = JSON.stringify(out, null, 1);
rmSync(OUT, { recursive: true, force: true });
const n = out.slots.reduce((s, x) => s + x.options.length, 0);

// --check compares rather than writes, so the gate and the tool share ONE
// definition of what the catalogue is. A gate that re-implements the transform
// it is checking is a second implementation to get wrong.
if (process.argv.includes("--check")) {
  if (!existsSync(path)) { console.error(`[exportarmoury] FAIL: no ${path} — run npm run exportarmoury`); process.exit(1); }
  const have = readFileSync(path, "utf8");
  if (have !== text) {
    console.error(`[exportarmoury] FAIL: the shipped catalogue is not what characters.ts says today.`);
    console.error(`  shipped ${have.length} bytes, current ${text.length} bytes — run npm run exportarmoury`);
    process.exit(1);
  }
  console.log(`[exportarmoury] ok: ${out.slots.length} slots, ${n} options, ${out.free.length} free — the shipped catalogue matches characters.ts`);
  process.exit(0);
}
writeFileSync(path, text);
console.log(`[exportarmoury] ${out.slots.length} slots, ${n} options, ${out.free.length} free -> StreamingAssets/armoury.json`);
